#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
LABEL="com.eres.notreparis.watchdog"
DOMAIN="gui/$(id -u)"
SERVICE_TARGET="$DOMAIN/$LABEL"
PLIST_PATH="$HOME/Library/LaunchAgents/$LABEL.plist"
CONFIG_PATH="$PROJECT_ROOT/.watchdog-service.conf"
LOG_DIR="$HOME/Library/Logs/NotreParis"
STDOUT_LOG="$LOG_DIR/watchdog.out.log"
STDERR_LOG="$LOG_DIR/watchdog.err.log"

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

require_file() {
    [[ -f "$1" ]] || die "Required file not found: $1"
}

load_service_config() {
    require_file "$CONFIG_PATH"
    # This file is generated by watchdog-install.sh and contains only VAULT_PATH.
    # shellcheck source=/dev/null
    source "$CONFIG_PATH"
    [[ -n "${VAULT_PATH:-}" ]] || die "VAULT_PATH is missing from $CONFIG_PATH"
    [[ -d "$VAULT_PATH/.obsidian" ]] || die "Not an Obsidian vault: $VAULT_PATH"
}

service_is_loaded() {
    launchctl print "$SERVICE_TARGET" >/dev/null 2>&1
}

bootstrap_service() {
    local attempt
    for attempt in 1 2 3 4 5; do
        if launchctl bootstrap "$DOMAIN" "$PLIST_PATH"; then
            return 0
        fi
        sleep 1
    done
    die "launchctl bootstrap failed after 5 attempts: $PLIST_PATH"
}
